server:
  port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: eureka
                    uri: https://github.com/fernandoEncalada/multiple-instances
                    search-paths: config-data
    application:
      name: config-service