server:
  port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: api-gateway
                    uri: https://github.com/fernandoEncalada/microservice
                    search-paths: config-data
    application:
      name: config-service
